CREATE TABLE REGION (
    id_region NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 21 INCREMENT BY 1 PRIMARY KEY,
    nombre_region VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE COMUNA (
    id_comuna NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1050 INCREMENT BY 5 PRIMARY KEY,
    nombre_comuna VARCHAR2(50) NOT NULL,
    id_region NUMBER NOT NULL,
    CONSTRAINT fk_comuna_region FOREIGN KEY (id_region) REFERENCES REGION(id_region),
    CONSTRAINT un_comuna UNIQUE (nombre_comuna, id_region)
);

CREATE TABLE PLANTA (
    id_planta NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 101 INCREMENT BY 1 PRIMARY KEY,
    nombre_planta VARCHAR2(50) NOT NULL,
    direccion VARCHAR2(100),
    id_comuna NUMBER NOT NULL,
    CONSTRAINT fk_planta_comuna FOREIGN KEY (id_comuna) REFERENCES COMUNA(id_comuna),
    CONSTRAINT un_planta UNIQUE(nombre_planta, id_comuna)
);

CREATE TABLE TURNO (
    id_turno NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    nombre_turno VARCHAR2(20) NOT NULL UNIQUE,
    hora_inicio CHAR(5) NOT NULL,
    hora_fin CHAR(5) NOT NULL
);

CREATE TABLE SALUD (
    id_salud NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 2000 INCREMENT BY 10 PRIMARY KEY,
    nombre_salud VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE AFP (
    id_afp NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    nombre_afp VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE CATEGORIA (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    nombre_categoria VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE TIPO_MAQUINA (
    id_tipo_maquina NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    nombre_tipo VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE MAQUINA (
    id_maquina NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1001 INCREMENT BY 1 PRIMARY KEY,
    numero_maquina NUMBER NOT NULL,
    nombre_maquina VARCHAR2(50) NOT NULL,
    activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N')),
    id_planta NUMBER NOT NULL,
    id_tipo_maquina NUMBER NOT NULL,
    CONSTRAINT fk_maquina_planta FOREIGN KEY (id_planta) REFERENCES PLANTA(id_planta),
    CONSTRAINT fk_maquina_tipo FOREIGN KEY (id_tipo_maquina) REFERENCES TIPO_MAQUINA(id_tipo_maquina),
    CONSTRAINT un_maquina UNIQUE (numero_maquina, id_planta)
);

CREATE TABLE EMPLEADO (
    id_empleado NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1001 INCREMENT BY 1 PRIMARY KEY,
    rut_empleado VARCHAR2(10) NOT NULL UNIQUE,
    nombres VARCHAR2(50) NOT NULL,
    apellido_paterno VARCHAR2(50) NOT NULL,
    apellido_materno VARCHAR2(50),
    fecha_contratacion DATE NOT NULL,
    sueldo_base NUMBER(10,2) NOT NULL,
    activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N')),
    id_planta NUMBER NOT NULL,
    id_salud NUMBER NOT NULL,
    id_afp NUMBER NOT NULL,
    id_jefe NUMBER,
    CONSTRAINT fk_empleado_planta FOREIGN KEY (id_planta) REFERENCES PLANTA(id_planta),
    CONSTRAINT fk_empleado_salud FOREIGN KEY (id_salud) REFERENCES SALUD(id_salud),
    CONSTRAINT fk_empleado_afp FOREIGN KEY (id_afp) REFERENCES AFP(id_afp),
    CONSTRAINT fk_empleado_jefe FOREIGN KEY (id_jefe) REFERENCES EMPLEADO(id_empleado)
);

CREATE TABLE JEFE_TURNO (
    id_empleado NUMBER PRIMARY KEY,
    area_responsabilidad VARCHAR2(50),
    max_operarios NUMBER,
    CONSTRAINT fk_jefe_empleado FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado)
);

CREATE TABLE OPERARIO (
    id_empleado NUMBER PRIMARY KEY,
    id_categoria NUMBER NOT NULL,
    certificacion VARCHAR2(50),
    horas_turno NUMBER DEFAULT 8,
    CONSTRAINT fk_operario_empleado FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado),
    CONSTRAINT fk_operario_categoria FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria)
);

CREATE TABLE TECNICO_MANTENCION (
    id_empleado NUMBER PRIMARY KEY,
    especialidad VARCHAR2(50),
    nivel_certificacion VARCHAR2(50),
    tiempo_respuesta NUMBER,
    CONSTRAINT fk_tecnico_empleado FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado)
);

CREATE TABLE ASIGNACION_TURNO (
    id_asignacion NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    id_empleado NUMBER NOT NULL,
    id_turno NUMBER NOT NULL,
    id_maquina NUMBER NOT NULL,
    fecha DATE NOT NULL,
    rol VARCHAR2(50),
    CONSTRAINT fk_asig_empleado FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado),
    CONSTRAINT fk_asig_turno FOREIGN KEY (id_turno) REFERENCES TURNO(id_turno),
    CONSTRAINT fk_asig_maquina FOREIGN KEY (id_maquina) REFERENCES MAQUINA(id_maquina),
    CONSTRAINT un_asig UNIQUE (id_empleado, fecha)
);

CREATE TABLE ORDEN_MANTENCION (
    id_orden NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    id_maquina NUMBER NOT NULL,
    id_tecnico NUMBER NOT NULL,
    fecha_programada DATE NOT NULL,
    fecha_ejecucion DATE,
    descripcion VARCHAR2(200),
    CONSTRAINT fk_orden_maquina FOREIGN KEY (id_maquina) REFERENCES MAQUINA(id_maquina),
    CONSTRAINT fk_orden_tecnico FOREIGN KEY (id_tecnico) REFERENCES TECNICO_MANTENCION(id_empleado),
    CONSTRAINT ck_fecha CHECK (fecha_ejecucion IS NULL OR fecha_ejecucion >= fecha_programada)
);

-- 3️⃣ INSERTAR DATOS INICIALES

-- 1. REGION
INSERT INTO REGION (nombre_region) VALUES ('Metropolitana');
INSERT INTO REGION (nombre_region) VALUES ('Valparaíso');

-- 2. COMUNA
INSERT INTO COMUNA (nombre_comuna, id_region) VALUES ('Santiago', 1);
INSERT INTO COMUNA (nombre_comuna, id_region) VALUES ('Valparaíso', 2);

-- 3. PLANTA
INSERT INTO PLANTA (nombre_planta, direccion, id_comuna) VALUES ('Planta Norte', 'Av. Norte 1234', 1);
INSERT INTO PLANTA (nombre_planta, direccion, id_comuna) VALUES ('Planta Sur', 'Av. Sur 5678', 2);

-- 4. TURNO
INSERT INTO TURNO (nombre_turno, hora_inicio, hora_fin) VALUES ('Mañana', '06:00', '14:00');
INSERT INTO TURNO (nombre_turno, hora_inicio, hora_fin) VALUES ('Tarde', '14:00', '22:00');
INSERT INTO TURNO (nombre_turno, hora_inicio, hora_fin) VALUES ('Noche', '22:00', '06:00');

-- 5. SALUD
INSERT INTO SALUD (nombre_salud) VALUES ('Fonasa');
INSERT INTO SALUD (nombre_salud) VALUES ('Isapre Cruz Blanca');

-- 6. AFP
INSERT INTO AFP (nombre_afp) VALUES ('AFP Habitat');
INSERT INTO AFP (nombre_afp) VALUES ('AFP Capital');

-- 7. CATEGORIA
INSERT INTO CATEGORIA (nombre_categoria) VALUES ('Moldeo Caliente');
INSERT INTO CATEGORIA (nombre_categoria) VALUES ('Moldeo Frío');

-- 8. TIPO_MAQUINA
INSERT INTO TIPO_MAQUINA (nombre_tipo) VALUES ('Horno');
INSERT INTO TIPO_MAQUINA (nombre_tipo) VALUES ('Línea IS');

-- 9. MAQUINA
INSERT INTO MAQUINA(numero_maquina, nombre_maquina, id_planta, id_tipo_maquina)
VALUES (1, 'Horno A', 1, 1);
INSERT INTO MAQUINA(numero_maquina, nombre_maquina, id_planta, id_tipo_maquina)
VALUES (2, 'Línea IS B', 1, 2);

-- 10. EMPLEADO
INSERT INTO EMPLEADO(rut_empleado, nombres, apellido_paterno, apellido_materno, fecha_contratacion, sueldo_base, id_planta, id_salud, id_afp)
VALUES ('12345678-9', 'Juan', 'Pérez', 'Gómez', TO_DATE('2023-01-01','YYYY-MM-DD'), 800000, 1, 1, 1);

INSERT INTO EMPLEADO(rut_empleado, nombres, apellido_paterno, apellido_materno, fecha_contratacion, sueldo_base, id_planta, id_salud, id_afp, id_jefe)
VALUES ('98765432-1', 'María', 'López', 'Rojas', TO_DATE('2023-02-01','YYYY-MM-DD'), 850000, 1, 2, 2, 1);

-- 11. OPERARIO
INSERT INTO OPERARIO(id_empleado, id_categoria, certificacion, horas_turno)
VALUES (1, 1, 'Certificación A', 8);

-- 12. TECNICO_MANTENCION
INSERT INTO TECNICO_MANTENCION(id_empleado, especialidad, nivel_certificacion, tiempo_respuesta)
VALUES (2, 'Hornos', 'Nivel 2', 2);

-- 13. ASIGNACION_TURNO
INSERT INTO ASIGNACION_TURNO(id_empleado, id_turno, id_maquina, fecha, rol)
VALUES (1, 1, 1, TO_DATE('2025-10-12','YYYY-MM-DD'), 'Operario');

-- 14. ORDEN_MANTENCION
INSERT INTO ORDEN_MANTENCION(id_maquina, id_tecnico, fecha_programada, descripcion)
VALUES (1, 2, TO_DATE('2025-10-15','YYYY-MM-DD'), 'Mantenimiento preventivo');



-- Informe 1: Turnos con inicio posterior a 20:00
SELECT nombre_turno AS TURNO,
       hora_inicio AS ENTRADA,
       hora_fin AS SALIDA
FROM TURNO
WHERE TO_DATE(hora_inicio, 'HH24:MI') > TO_DATE('20:00','HH24:MI');

-- Informe 2: Turnos diurnos entre 06:00 y 14:59
SELECT nombre_turno AS TURNO,
       hora_inicio AS ENTRADA,
       hora_fin AS SALIDA
FROM TURNO
WHERE TO_DATE(hora_inicio, 'HH24:MI') BETWEEN TO_DATE('06:00','HH24:MI') 
                                        AND TO_DATE('14:59','HH24:MI');

--Asignaciones de turnos por día
 SELECT a.fecha, e.nombres, e.apellido_paterno, t.nombre_turno, m.nombre_maquina
FROM ASIGNACION_TURNO a
JOIN EMPLEADO e ON a.id_empleado = e.id_empleado
JOIN TURNO t ON a.id_turno = t.id_turno
JOIN MAQUINA m ON a.id_maquina = m.id_maquina;      

-- 1. Ver todas las regiones
SELECT * FROM REGION;

-- 2. Ver todas las comunas con su región
SELECT c.nombre_comuna, r.nombre_region
FROM COMUNA c
JOIN REGION r ON c.id_region = r.id_region;

-- 3. Ver plantas y su comuna
SELECT p.nombre_planta, p.direccion, c.nombre_comuna
FROM PLANTA p
JOIN COMUNA c ON p.id_comuna = c.id_comuna;

-- 4. Ver máquinas y su tipo
SELECT m.nombre_maquina, m.numero_maquina, t.nombre_tipo AS tipo_maquina, p.nombre_planta
FROM MAQUINA m
JOIN TIPO_MAQUINA t ON m.id_tipo_maquina = t.id_tipo_maquina
JOIN PLANTA p ON m.id_planta = p.id_planta;

-- 5. Ver empleados y su planta, salud y AFP
SELECT e.nombres || ' ' || e.apellido_paterno AS nombre_completo,
       p.nombre_planta, s.nombre_salud, a.nombre_afp
FROM EMPLEADO e
JOIN PLANTA p ON e.id_planta = p.id_planta
JOIN SALUD s ON e.id_salud = s.id_salud
JOIN AFP a ON e.id_afp = a.id_afp;

-- 6. Ver operarios y su categoría
SELECT o.id_empleado, e.nombres || ' ' || e.apellido_paterno AS nombre_empleado,
       c.nombre_categoria, o.certificacion, o.horas_turno
FROM OPERARIO o
JOIN EMPLEADO e ON o.id_empleado = e.id_empleado
JOIN CATEGORIA c ON o.id_categoria = c.id_categoria;

-- 7. Ver técnicos de mantención y su especialidad
SELECT t.id_empleado, e.nombres || ' ' || e.apellido_paterno AS nombre_empleado,
       t.especialidad, t.nivel_certificacion, t.tiempo_respuesta
FROM TECNICO_MANTENCION t
JOIN EMPLEADO e ON t.id_empleado = e.id_empleado;

-- 8. Ver asignaciones de turno
SELECT a.fecha, e.nombres || ' ' || e.apellido_paterno AS empleado,
       t.nombre_turno, m.nombre_maquina, a.rol
FROM ASIGNACION_TURNO a
JOIN EMPLEADO e ON a.id_empleado = e.id_empleado
JOIN TURNO t ON a.id_turno = t.id_turno
JOIN MAQUINA m ON a.id_maquina = m.id_maquina;

-- 9. Ver órdenes de mantención con máquina y técnico asignado
SELECT o.id_orden, m.nombre_maquina, e.nombres || ' ' || e.apellido_paterno AS tecnico,
       o.fecha_programada, o.fecha_ejecucion, o.descripcion
FROM ORDEN_MANTENCION o
JOIN MAQUINA m ON o.id_maquina = m.id_maquina
JOIN TECNICO_MANTENCION t ON o.id_tecnico = t.id_empleado
JOIN EMPLEADO e ON t.id_empleado = e.id_empleado;

